### ISSUE TITLE
Updating to flow-emulator 0.50.7 fails on tests

### ISSUE THREAD

**Issue by andrewanchorage** [onflow/flow-cli#1099] opened 2023-06-20 23:02 UTC
### Problem

Running `make test` after running `go get github.com/onflow/flow-emulator` in root and ./flowkit causes error

```
TestExecutingTests/with_file_read (0.69s)
...
Execution failed:
error: internal error: runtime error: index out of range [1] with length 0
                                goroutine 15 [running]:
                                runtime/debug.Stack()
                                        go/src/runtime/debug/stack.go:24 +0x65
                                github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
                                        go/pkg/mod/github.com/onflow/cadence@v0.39.8/runtime/errors/errors.go:152
                                github.com/onflow/cadence/runtime/interpreter.(*Interpreter).RecoverErrors(0xc004beaea0, 0x1a1d008)
                                        go/pkg/mod/github.com/onflow/cadence@v0.39.8/runtime/interpreter/interpreter.go:528 +0x14e
                                panic({0x17b6180, 0xc005e684c8})
                                        go/src/runtime/panic.go:884 +0x213
                                github.com/onflow/cadence-tools/test.(*LogCollectionHook).Run(0xc004d82d68, 0xbfe319?, 0x0?, {0x189cddb?, 0x411cca?})
                                        go/pkg/mod/github.com/onflow/cadence-tools/test@v0.9.0/test_runner.go:97 +0x135
                                github.com/rs/zerolog.(*Event).msg(0xc000b740c0, {0x189cddb, 0x19})
                                        go/pkg/mod/github.com/rs/zerolog@v1.29.0/event.go:141 +0x8f
                                github.com/rs/zerolog.(*Event).Msg(...)
                                        go/pkg/mod/github.com/rs/zerolog@v1.29.0/event.go:108
                                github.com/onflow/flow-emulator/utils.PrintTransactionResult(0xc004da8000?, 0xc000f48500)
                                        go/pkg/mod/github.com/onflow/flow-emulator@v0.50.7/utils/logging.go:64 +0x21c
                                github.com/onflow/flow-emulator/emulator.(*Blockchain).executeAndCommitBlock(0xc004da8000)
                                        go/pkg/mod/github.com/onflow/flow-emulator@v0.50.7/emulator/blockchain.go:1329 +0xe5
                                github.com/onflow/flow-emulator/emulator.(*Blockchain).ExecuteAndCommitBlock(0xc004da8000)
                                        go/pkg/mod/github.com/onflow/flow-emulator@v0.50.7/emulator/blockchain.go:1312 +0x94
                                github.com/onflow/flow-emulator/emulator.deployContract(0x1bc8090?, {0x1879683, 0x4}, {0xc000394000, 0x1cdf, 0x28b8260?})
                                        go/pkg/mod/github.com/onflow/flow-emulator@v0.50.7/emulator/contracts.go:118 
```
### Steps to Reproduce

1. Update flow-emulator
2. run make test

**Comment by peterargue** [comment] 2023-06-21 18:40
from that backtrace, it looks like there's a bug in version of `cadence-tools` used in `flow-cli`. Looks like it was fixed already on master:
https://github.com/onflow/cadence-tools/commit/c653483149258944243937d8e03de6fc03fd70ec

**Comment by chasefleming** [comment] 2023-06-21 18:51
I've merged the PR to upgrade cadence tools to 0.9.1 https://github.com/onflow/flow-cli/pull/1079

**Comment by peterargue** [comment] 2023-06-21 18:54
I don't think the fix is included on 0.9.1. we'll need to tag a new release. @turbolent can you help with that?

**Comment by chasefleming** [comment] 2023-06-21 18:55
Thanks @peterargue , yeah I just merged the PR to upgrade cadence tools to 0.9.1 https://github.com/onflow/flow-cli/pull/1079

But looks to be still failing though after re-running the job to upgrade emulator: https://github.com/onflow/flow-cli/pull/1100

**Comment by m-Peter** [comment] 2023-06-22 09:33
This is actually my fault :innocent:
Looking at this diff here: https://github.com/onflow/cadence-tools/compare/test/v0.9.1...master
the commit which fixed the issue is this one: https://github.com/onflow/cadence-tools/commit/c653483149258944243937d8e03de6fc03fd70ec.
However, it is not included in that release.
Kudos on the investigation @peterargue :raised_hands:

**Comment by chasefleming** [comment] 2023-06-23 18:34
Resolved here: https://github.com/onflow/flow-cli/pull/1101

**Closed by chasefleming** 2023-06-23 18:34 UTC
Labels: Feedback
