### ISSUE TITLE
Escaping characters in Strings is misbehaving

### ISSUE THREAD

**Issue by Screendead** [onflow/flow-cli#450] opened 2022-01-24 19:58 UTC
### Problem

Escaping characters leaves the backslash in the resulting string.

### Steps to Reproduce

1. Create a script with the following (try replacing the second backslash with " or n to test quotemark literal characters and newline characters):
 ```
pub fun main(): String {
    return "\\";
}
```
2. run flow scripts execute [path-to-file] --network testnet

### Expected result

(note: the output is always wrapped with quote marks)

Output:
> Result: "\"

With " character instead:
> Result: """

### Actual result

Output:
> Result: "\\"

With " character instead:
> Result: "\""

When interacting with this script via @onflow/fcl, result is the following error:
>[Error Code: 1101] cadence runtime error Execution failed:
error: invalid end of string literal: missing '"'

**Comment by sideninja** [comment] 2022-03-07 14:41
@dsainati1 should this be moved to Cadence or do you think it's a CLI issue?

**Comment by sideninja** [comment] 2022-03-07 15:10
I see. Will try to pinpoint the issue and solve it.

**Comment by bluesign** [comment] 2022-07-30 08:58
I think this is not bug it is by design ( the reason Result is always wrapped in double quotes)

What is inside double quotes, is always escaped string.

**Comment by sideninja** [comment] 2022-08-01 08:57
I think it's fair to close this issue then.

**Closed by sideninja** 2022-08-01 08:57 UTC
Labels: L3
