### ISSUE TITLE
`flow dev` removed all accounts defined in the `flow.json`

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-cli#1061] opened 2023-06-05 16:54 UTC
### Instructions

Given the command `flow dev`
```sh
flow --help 

🔥 Super Commands
  dev          Build your Flow project
```

and the `Flow.json` file containing an account
```json
"accounts": {
		"AccountA": {
			"address": "01cf0e2f2f715450",
			"key": "..."
		}
}
```

the command
```sh
flow dev
```

removes the account from the `flow.json`.

Expected: create the account or not remove the definition.

### Problem

<what is the problem you've encountered?>

### Steps to Reproduce

<share any logs/screenshots or steps to replicate>

### Acceptance Criteria

<if any>

### Context

<what are you currently working on that this is blocking?>

**Comment by cybercent** [comment] 2023-06-05 17:05
Also it's unclear what `flow dev` does.

When running `flow dev` it adds a `default` entry in the `flow.json` file where it duplicates all contract names found under the `emulator-account` entry and then it complains that it can't deploy the same contracts on multiple accounts.

When removing the `emulator-account` and keeping only the `default` the CLI errors with `no default emulator account`.

**Comment by chasefleming** [comment] 2023-06-05 23:37
@cybercent what version of CLI are you using?

**Comment by cybercent** [comment] 2023-06-06 09:10
```sh
Version: v1.1.1
```

**Comment by chasefleming** [comment] 2023-06-07 00:13
I cannot reproduce the issue with the example you gave. For the second issue, the "default" account is for contracts created without a folder. Other accounts get created based on the folder structure of `contracts/`. e.g. If you created a folder under contracts as `FooBar` and then a contract called `HelloWorld.cdc`, you'd have an account called `FooBar` deploying a contract called `HelloWorld`. Whereas, if you added it directly under the contracts folder it would be deployed to `default`. Emulator account is separate from your created accounts. Ideally, using "flow dev" one shouldn't be deleting or adding accounts on emulator and should let "flow dev" handle it all for you. What is the desired behavior you'd like to see?

**Comment by btspoony** [comment] 2023-07-25 04:18
In version 1.3.2, the `flow dev` command stiil deletes the `accounts` I defined and also removes the `FungibleToken` I added.
At the same time, removing `FungibleToken` causes an error in Language Server for `MetadataViews.cdc`, resulting in all CDCs that use `MetadataViews` doesn't work.

**Comment by sideninja** [comment] 2023-07-26 12:49
> Also it's unclear what `flow dev` does.
> 
> When running `flow dev` it adds a `default` entry in the `flow.json` file where it duplicates all contract names found under the `emulator-account` entry and then it complains that it can't deploy the same contracts on multiple accounts.
> 
> When removing the `emulator-account` and keeping only the `default` the CLI errors with `no default emulator account`.

@cybercent the issue you are seeing is likely because you are managing flow.json manually as well as by using flow dev. Flow dev should manage the flow.json for you. The problem with deploying the same contracts on multiple accounts is that you (I assume, and please correct me if I'm wrong) manually added deployments for the emulator account (or maybe by using the add-contract command), and then used the flow dev command which also added those contracts to deployment section. It then complains it can't deploy to both accounts on the same network. The solution would be to remove the deployments on the emulator account from the deployments section, but not to remove the emulator account from the accounts section as it's needed to run the emulator. 
This might be confusing and if you manually managed flow.json that is usually why things get confusing, but if you somehow get to this state without manually editing flow.json please do let me know since then we should think about how to prevent states like this.

**Comment by sideninja** [comment] 2023-07-26 12:54
@btspoony 
> the flow dev command stiil deletes the accounts I defined 

You created an account using flow CLI on the emulator and it was added to flow.json, then running flow dev removed that account for you? I'm trying to reproduce this but no luck, so if you can define a better step-by-step instructions how to reproduce it will be easier.

> also removes the FungibleToken I added

Couldn't reproduce that either, can you give me step-by-step instructions?

**Comment by btspoony** [comment] 2023-07-26 13:46
Sure!
Step 0: 
Here is an empty project with imported modules.
<img width="263" alt="QQ20230726-211327@2x" src="https://github.com/onflow/flow-cli/assets/707025/2a18601f-a9b3-491e-a0e9-97293a3ec470">
And Initialized `flow.json`
```
{
  "contracts": {
    "AddressUtils": {
      "source": "./modules/flow-utils/cadence/contracts/AddressUtils.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "a340dc0a4ec828ab",
        "testnet": "31ad40c07a2a9788"
      }
    },
    "ArrayUtils": {
      "source": "./modules/flow-utils/cadence/contracts/ArrayUtils.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "a340dc0a4ec828ab",
        "testnet": "31ad40c07a2a9788"
      }
    },
    "CapabilityDelegator": {
      "source": "./modules/hybrid-custody/contracts/CapabilityDelegator.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "CapabilityFactory": {
      "source": "./modules/hybrid-custody/contracts/CapabilityFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "CapabilityFilter": {
      "source": "./modules/hybrid-custody/contracts/CapabilityFilter.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "FTAllFactory": {
      "source": "./modules/hybrid-custody/contracts/factories/FTAllFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "FTProviderFactory": {
      "source": "./modules/hybrid-custody/contracts/factories/FTProviderFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "FlowToken": {
      "source": "",
      "aliases": {
        "emulator": "0ae53cb6e3f42a79",
        "mainnet": "1654653399040a61",
        "testnet": "7e60df042a9c0868"
      }
    },
    "FungibleToken": {
      "source": "./modules/flow-nft/contracts/utility/FungibleToken.cdc",
      "aliases": {
        "emulator": "ee82856bf20e2aa6",
        "mainnet": "f233dcee88fe0abe",
        "testnet": "9a0766d93b6608b7"
      }
    },
    "HybridCustody": {
      "source": "./modules/hybrid-custody/contracts/HybridCustody.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "MetadataViews": {
      "source": "./modules/flow-nft/contracts/MetadataViews.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "1d7e57aa55817448",
        "testnet": "631e88ae7f1d7c20"
      }
    },
    "NFTCollectionPublicFactory": {
      "source": "./modules/hybrid-custody/contracts/factories/NFTCollectionPublicFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "NFTProviderAndCollectionFactory": {
      "source": "./modules/hybrid-custody/contracts/factories/NFTProviderAndCollectionFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "NFTProviderFactory": {
      "source": "./modules/hybrid-custody/contracts/factories/NFTProviderFactory.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "testnet": "294e44e1ec6993c6"
      }
    },
    "NonFungibleToken": {
      "source": "./modules/flow-nft/contracts/NonFungibleToken.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "1d7e57aa55817448",
        "testnet": "631e88ae7f1d7c20"
      }
    },
    "StringUtils": {
      "source": "./modules/flow-utils/cadence/contracts/StringUtils.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "a340dc0a4ec828ab",
        "testnet": "31ad40c07a2a9788"
      }
    },
    "ViewResolver": {
      "source": "./modules/flow-nft/contracts/ViewResolver.cdc",
      "aliases": {
        "emulator": "f8d6e0586b0a20c7",
        "mainnet": "1d7e57aa55817448",
        "testnet": "631e88ae7f1d7c20"
      }
    }
  },
  "networks": {
    "emulator": "127.0.0.1:3569",
    "mainnet": "access.mainnet.nodes.onflow.org:9000",
    "sandboxnet": "access.sandboxnet.nodes.onflow.org:9000",
    "testnet": "access.devnet.nodes.onflow.org:9000"
  },
  "accounts": {
    "default": {
      "address": "e03daebed8ca0615",
      "key": "625fa26301b5d54d3be6aec70213c8c9a0dcb4bd22a78041cb0d8c6e7d19627e"
    },
    "emulator-account": {
      "address": "f8d6e0586b0a20c7",
      "key": "625fa26301b5d54d3be6aec70213c8c9a0dcb4bd22a78041cb0d8c6e7d19627e"
    }
  },
  "deployments": {
    "emulator": {
      "emulator-account": [
        "NonFungibleToken",
        "MetadataViews",
        "ViewResolver",
        "AddressUtils",
        "StringUtils",
        "ArrayUtils",
        "CapabilityDelegator",
        "CapabilityFilter",
        "CapabilityFactory",
        "HybridCustody",
        "FTProviderFactory",
        "FTAllFactory",
        "NFTProviderFactory",
        "NFTProviderAndCollectionFactory",
        "NFTCollectionPublicFactory"
      ]
    }
  }
}
```
Now run `flow emulator` and `flow dev`
```
"deployments": {
    "emulator": {
      "default": []
    }
  }
``` 
`default` will be added to `deployments` in `flow.json`

Now add a new Contract:
```
import "MetadataViews"

pub contract MyContract {

}
```

run `flow dev` again.
```
	"deployments": {
		"emulator": {
			"default": [
				"MyContract"
			]
		}
	}
```
`flow.json` updated 
and the issue occurred.
![3](https://github.com/onflow/flow-cli/assets/707025/e52b9726-27bc-4b9f-b91b-d491e297619a)
![4](https://github.com/onflow/flow-cli/assets/707025/38862666-e2fd-43cb-aa64-d337a215a50a)
![5](https://github.com/onflow/flow-cli/assets/707025/4980c4c1-ba0f-4420-a4f0-333518a3705a)

**Note that everything looks fine at the beginning.** 
However, this error occurred as soon as I made some edits to `MyContract`.

---
> How to resolve:

Manually add this.
![ft](https://github.com/onflow/flow-cli/assets/707025/54aee179-749b-4773-a050-2090f6f758a1)
And restart the emulator
![fine](https://github.com/onflow/flow-cli/assets/707025/184da24c-9d4b-4e35-bc4d-1c389a9ea7d1)
And now it will be fine.

But if I run the `flow dev` again.
![gone](https://github.com/onflow/flow-cli/assets/707025/877c0138-562e-444b-9ed0-496c7ac7ceb3)
The `ft` is gone.

BTW, FungibleToken contract should be default when emulator started
![111](https://github.com/onflow/flow-cli/assets/707025/2d5351d5-f587-4d21-bceb-6b77db86a1f0)

**Comment by btspoony** [comment] 2023-07-26 13:54
BTW, My Indent is **space** not **tab**
I suspect it is related to this.

**Comment by sideninja** [comment] 2023-07-27 14:20
If an account doesn't exist on the emulator network it will remove it, this is because flow dev manages the accounts for you. If you want to manually manage accounts then you must make sure accounts actually exist before running flow dev, otherwise flow dev will remove them as it can't guarantee same addresses will be used for accounts that are being created by flow dev. Hence closing this issue. We will however add this as part of the documentation.

**Closed by sideninja** 2023-07-27 14:20 UTC
Labels: Feedback
