### ISSUE TITLE
Advanced contract config without aliases 

### ISSUE THREAD

**Issue by bluesign** [onflow/flow-cli#695] opened 2022-11-12 18:26 UTC
### Instructions

This came on discord, not sure if it is a bug. 

When contract is defined like below:
```
 "YoungApeDiaries": {
            "source": "./contracts/YoungApeDiaries.cdc"
},
```
it fails to deploy. ( as aliases are empty ). 

I don't know much about code there, but I think I can fix it if it is a bug.

**Comment by sideninja** [comment] 2022-11-14 14:06
In the case above you should use another format:

`"YoungApeDiaries": "./contracts/YoungApeDiaries.cdc"`

So the format is not really valid and hence not a bug, but it's valid to say that we should detect this and warn the user about the invalid format.

**Comment by sideninja** [comment] 2022-11-15 12:10
Aliases will get deprecated soon anyway with some improvements to flow.json so I will just close this as I don't think it's necessary an issue. We have flow.json validation issue already open.

**Closed by sideninja** 2022-11-15 12:10 UTC
Labels: Feedback
