### ISSUE TITLE
Flow CLI Version v1.3.4 crashes on height check

### ISSUE THREAD

**Issue by jmtx1020** [onflow/flow-cli#1169] opened 2023-08-24 17:21 UTC
### Instructions

I installed the setup as normal.

```
sh -ci "$(curl -fsSL https://raw.githubusercontent.com/onflow/flow-cli/master/install.sh)"
```

### Problem

When I try to check the height of my node, it crashes.

### Steps to Reproduce

```
~$ flow blocks get latest --host localhost:9000

❌ Crash detected!

Use the arrow keys to navigate: ↓ ↑ → ←
? 🙏 Please report the crash so we can improve the CLI. Do you want to report it?:
  ▸ Yes, report the crash
    No
```

**Comment by jribbink** [comment] 2023-08-24 17:39
Hey @jmtx1020 , this is a known bug (duplicate of https://github.com/onflow/flow-cli/issues/1160) and there is a fix on the way.

However, to use this functionality in the short term, you can run this command in a folder with a `flow.json` file or run `flow init` first.

**Comment by chasefleming** [comment] 2023-08-24 20:07
#1160 is closed so closing this as well. Fix will be out next release.

**Closed by chasefleming** 2023-08-24 20:07 UTC
Labels: Feedback
